### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by djcomy** [Vinodh-G/VSCollectionKit#1]
Won't even start - Reason: image not found

**Comment by Vinodh-G** [comment]
@djcomy 

Can you elaborate little,  are you get "Reason: image not found" when testing Test App target?

Or 

You tried using it in your project and you are getting "Reason: image not found"?

**Comment by Vinodh-G** [comment]
If using VSCollectionkit in your project.
You have to **embed vscollectionkit.framework** in your build phase embed framework section.

Something similar as shown below used in the NewsApp.
<img width="1056" alt="B337147C-70E1-4052-9CAB-31648F76AEFD" src="https://user-images.githubusercontent.com/5305527/81490517-cbcf3b00-92a0-11ea-8e82-ffd29de1a025.png">
